### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by PallHaraldsson** [GenieFramework/GeniePackageManager.jl#2]
I'm intrigued you have (and need?) a package manger, at least you have a typo:

"GUI based packae manager for GenieFramework" -> "GUI-based package manager for GenieFramework"

**Comment by AbhimanyuAryan** [comment]
yes I am aware of that but I don't have the permission to change it. I'll have to ask Adrian to modify it 

Need. This is for GenieBuilder (our no-code editor): https://marketplace.visualstudio.com/items?itemName=GenieBuilder.geniebuilder

**Comment by PallHaraldsson** [comment]
In case the typo was in two+ places, I meant at https://github.com/GenieFramework/GeniePackageManager.jl to the right, and it's still there.

I would just keep the issue open until @essenciary sees it and fixes.

And https://genieframework.com/#genie-section links to Genie.jl, maybe it should link (rather, or too) to this new meta-package?

At first I thought this package was https://geniecloud.io/ but it seems not (though likely part of it). Looking forward to seeing it public!

**Comment by AbhimanyuAryan** [comment]
@PallHaraldsson sure re-opened. This package will be injected to GenieCloud

**Comment by essenciary** [comment]
I will be openly available to anybody to add to their Genie apps (so not restricted to the cloud components).

**Comment by PallHaraldsson** [comment]
@essenciary the typo is still there, maybe forgotten (then issue can be closed). Looking forward to Genie Cloud!

**Comment by AbhimanyuAryan** [comment]
@PallHaraldsson yes aware of that. Adrian is super busy will ask him later

**Comment by AbhimanyuAryan** [comment]
@PallHaraldsson the typo is fixed. I'll close this now
