### ISSUE TITLE
Doc question - outdated?

### ISSUE THREAD

**Issue by PallHaraldsson** [GenieFramework/GeniePackageManager.jl#5]
I see in Genie's main docs: "and versioning and dependency management is provided by Julia's own Pkg." Is it outdated because of this new package manager I just discovered but haven't yet explored.

**Comment by AbhimanyuAryan** [comment]
@PallHaraldsson no Genie Docs is not outdated. This package manager is a GUI based alternative to Julia's PKG specially inside GenieBuilder. If you have Genie application(not inside GenieBuilder) I recommend using Pkg instead of GPM(Genie Package Manager)
